name: Test

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.0.3
          elixir-version: 1.13.4
      - name: Compile and Test
        run: |
          mix deps.get
          mix test
    
  macos:
    runs-on: macos-11
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v3
      - name: macOS setup
        run: |
          brew install erlang elixir
          mix local.hex --force
          mix local.rebar --force
      - name: Compile and Test
        run: |
          mix deps.get
          mix test

  windows-nmake:
    runs-on: windows-latest
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25.0.2
          elixir-version: 1.13.4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      - name: Compile and Test
        shell: bash
        run: |
          mix deps.get
          mix compile
          ls -la _build/test/lib/castore/priv
          mix test || true
          ls -la _build/test/lib/castore/priv

  # windows-mingw32-msys2:
  #   runs-on: windows-latest
  #   env:
  #     MIX_ENV: test
  #   defaults:
  #     run:
  #       shell: msys2 {0}
  #   steps:
  #     - uses: msys2/setup-msys2@v2
  #       with:
  #         update: true
  #         install: >-
  #           base-devel
  #           git
  #     - uses: actions/checkout@v3
  #     - uses: erlef/setup-beam@v1
  #       with:
  #         otp-version: 25.0.2
  #         elixir-version: 1.13.4
  #     - name: Compile and Test
  #       run: |
  #         export INSTALL_DIR_FOR_ELIXIR=$(echo "/${INSTALL_DIR_FOR_ELIXIR}" | sed -e "s#\\\\#/#" | sed -e "s#:##")
  #         export INSTALL_DIR_FOR_OTP=$(echo "/${INSTALL_DIR_FOR_OTP}" | sed -e "s#\\\\#/#" | sed -e "s#:##")
  #         echo "INSTALL_DIR_FOR_ELIXIR: ${INSTALL_DIR_FOR_ELIXIR}"
  #         echo "INSTALL_DIR_FOR_OTP: ${INSTALL_DIR_FOR_OTP}"
  #         export PATH="${INSTALL_DIR_FOR_ELIXIR}/bin:${INSTALL_DIR_FOR_OTP}/bin:${PATH}"
  #         pacman -S --noconfirm pacman-mirrors pkg-config
  #         pacman -S --noconfirm --needed base-devel autoconf automake make libtool git \
  #           mingw-w64-x86_64-toolchain mingw-w64-x86_64-openssl mingw-w64-x86_64-libtool
  #         mix deps.get
  #         mix test
