name: playground-arm64-macos

on:
  workflow_dispatch:
    inputs:
      os:
        default: "macos-14"
        required: true

jobs:
  windows:
    runs-on: ${{ inputs.os }}
    steps:
      - run: |
          export WXWIDGETS_FILENAME="wxWidgets-static-arm64-apple-darwin.tar.gz"
          curl -fSL "https://github.com/cocoa-xu/wxWidgets-build/releases/download/v3.2.6/${WXWIDGETS_FILENAME}" -o "${WXWIDGETS_FILENAME}"
          sudo tar -C "/usr/local" -xf "${WXWIDGETS_FILENAME}"
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
