name: playground

on:
  workflow_dispatch:
    inputs:
      os:
        default: "ubuntu-latest"
        required: true
      otp_version:
        default: "26"
        required: true
      elixir_version:
        default: "1.16"
        required: true

jobs:
  windows:
    runs-on: ${{ inputs.os }}

    services:
      pg:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    
    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ inputs.otp_version }}
          elixir-version: ${{ inputs.elixir_version }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
