name: Test

on:
  workflow_dispatch:
    inputs:
      os:
        default: "macos-11"
        required: true

jobs:
  windows:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Show disk space
        run: |
          df -h
      - name: free disk space
        shell: bash
        if: contains(runner.os, 'ubuntu')
        run: |
          bash ./free-disk-space.sh
