name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  windows:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Install GStreamer
        uses: blinemedical/setup-gstreamer@v1.4.0
        with:
          version: "1.24.5"
          arch: "x86_64"
