name: Test

on:
  workflow_dispatch:
    inputs:
      os:
        default: "ubuntu-latest"
        required: true

jobs:
  windows:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Show head commit
        run: |
          echo ${{ github.event.head_commit.id }}
          echo $(git rev-parse HEAD)
