name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show head commit
        run: |
          echo ${{ github.event.head_commit.id }}
          echo $(git rev-parse HEAD)
