name: playground-linux

on:
  workflow_dispatch:
    inputs:
      os:
        default: "ubuntu-22.04"
        required: true

jobs:
  linux:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Step 1
        continue-on-error: true
        run: |
          exit 1

      - name: Step 2
        continue-on-error: true
        run: |
          echo ok

      - name: Step 3
        continue-on-error: true
        run: |
          exit 2
