name: playground-linux

on:
  workflow_dispatch:
    inputs:
      os:
        default: "ubuntu-22.04"
        required: true

jobs:
  linux:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Install GStreamer
        id: setup_gstreamer
        uses: blinemedical/setup-gstreamer@v1.4.0
        with:
          version: "1.22.12"
          arch: "x86_64"

      - name: Cache GStreamer
        id: cache-gstreamer
        run: |
          echo "${{ steps.setup_gstreamer.outputs.gstreamerPath }}"

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
