name: playground

on:
  workflow_dispatch:
    inputs:
      os:
        default: "windows-2019"
        required: true
      otp_version:
        default: "26"
        required: true
      elixir_version:
        default: "1.16"
        required: true

jobs:
  windows:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ inputs.otp_version }}
          elixir-version: ${{ inputs.elixir_version }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
