name: windows-cuda

on:
  workflow_dispatch:
    inputs:
      os:
        default: "windows-2019"
        required: true

jobs:
  windows:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Install CUDA with cudnn ${{ matrix.pair.cudnn_major }}
        uses: cocoa-xu/cuda-toolkit@v0.6.0
        with:
          cuda: 12.5.0
          cudnn: 9.2.0
      - name: Setup tmate session
        if: always()
        uses: mxschmitt/action-tmate@v3
