name: windows

on:
  workflow_dispatch:
    inputs:
      os:
        default: "windows-2019"
        required: false

jobs:
  windows:
    runs-on: ${{ inputs.os }}
    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "21.0"
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
