name: linux-precompile-musl

on:
  push:
    branches:
      - main

jobs:
  mix_test:
    runs-on: ubuntu-20.04
    container: alpine:latest
    steps:
      - name: Mix compile
        run: |
          mkdir -p _build/dev/lib/evision/priv
          echo "hello" > _build/dev/lib/evision/priv/evision.so
          pwd
          ls -la

      - name: Create precompiled library
        run: |
          pwd
          ls -la
          cat _build/dev/lib/evision/priv/evision.so
